spring:
  application:
    name: authentication-service
  mvc:
    servlet:
      path: /authentication-service

server:
  port: 9200

eureka:
  instance:
    hostname: localhost
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka